accounts/urls.py
from django.urls import path, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from .views import login_view,logout_view,register_view
from django.contrib.auth import views as auth_view


app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('password-reset/', auth_view.PasswordResetView.as_view(template_name='password_reset_form.html', success_url=reverse_lazy('accounts:password_reset_done'), email_template_name='password_reset_email.html'), name='password_reset'),
    path('password-reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_view.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

cart/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace = 'shop')),
    path('cart/', include('cart.urls', namespace = 'cart')),
    path('account/', include('accounts.urls', namespace = 'accounts')),
    path('order/', include('orders.urls', namespace = 'orders')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/',views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('products/', views.product, name='product'),
    path('products/category/<slug:category_slug>/', views.product, name='category'),
    path('product/<int:product_id>/', views.product_detail, name = 'product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICE = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices = PRODUCT_QUANTITY_CHOICE,
        coerce=int,
        initial=1,
        widget=forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'min': '1', 'style':'width:60px; text-align:center;'})
    )
    override = forms.BooleanField(
        required = False,
        initial=False,
        widget= forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override']
        )
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@login_required
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True}
        )
    return render(request, 'cart/cart.html', {'cart':cart})

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Shopping Cart {% endblock title %}
   
{% block main-content %}
   <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand fw-bold text-primary" href="#">TommyTech Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'shop:homepage' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'shop:product' %}">Products</a></li>
                
            </ul>
            <ul class="navbar-nav ms-auto">
                {% with total_items=cart|length %}
                    {% if total_items > 0 %}                   
						<li class="nav-item"><a class="nav-link position-relative" href="{% url 'cart:cart_detail' %}">Your cart: {{total_items}} item{{ total_items|pluralize }},&#9;${{ cart.get_total_price }}
                </a></li>
					{% elif not order %}
						<li class="nav-item"><a class="nav-link position-relative">Your cart is empty</a>      
                </li>
					{% endif %}
                {% endwith%}
				<form action="{% url 'accounts:logout' %}" method="post">
                        <button type="submit" class="btn btn-danger">Logout</button>
                        {% csrf_token %}
                </form>
            </ul>
        </div>
    </div>
</nav>

<div class="main-content">
        <!-- Your Page Content Here -->
    
    <!-- Cart Content -->
    <div class="container my-5">
        <h2 class="mb-4">Your Shopping Cart</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Action</th>
                    <th>Unit Price</th>
                    <th>Price</th>
                    
                </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}           
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url}}">
                            <img src="{% if product.image %}{{product.image.url}}{% else %}{{product.name}}{% endif %}" class="img-fluid img-thumbnail" style="max-width: 100px; height: auto;">
                        </a>
                    </td>
                    <td>{{product.name}}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post" class="d-flex align-items-center">
                            {{ item.update_quantity_form.quantity}}
                            {{ item.update_quantity_form.override }}
                            <input type="submit" value="update" class="btn btn-success btn-sm" style="margin-left:5px;">
                            {% csrf_token %}
                            
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Remove" class="btn btn-danger btn-sm">
                        </form>
                    </td>
                    <td>${{item.price}}</td>
                    <td>${{item.total_price}}</td>
                </tr>
                {% endwith %}
            {% endfor %}
        <!-- To display total price -->
                <tr>
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td>${{ cart.get_total_price }}</td>
                </tr>
            </tbody>
        </table>
        <p class="text-end">
            <a href="{% url 'shop:product' %}" class="btn btn-light text-dark btn-sm btn-md-lg w-auto mb-2">Continue Shopping</a>
            <a href="{% url 'orders:order_create' %}" class="btn btn-primary btn-sm btn-md-lg w-auto">Proceed to Checkout</a>
        </p>
        
    </div>
</div>
{% endblock main-content %}