accounts/urls.py
from django.urls import path, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from .views import login_view,logout_view,register_view
from django.contrib.auth import views as auth_view


app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('password-reset/', auth_view.PasswordResetView.as_view(template_name='password_reset_form.html', success_url=reverse_lazy('accounts:password_reset_done'), email_template_name='password_reset_email.html'), name='password_reset'),
    path('password-reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_view.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

cart/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace = 'shop')),
    path('cart/', include('cart.urls', namespace = 'cart')),
    path('account/', include('accounts.urls', namespace = 'accounts')),
    path('order/', include('orders.urls', namespace = 'orders')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login,logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages



def register_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        
        #Validate passwords
        if password1 != password2:
            messages.error(request,'Passwords do not match')
            return redirect('accounts:register')
        
        #Check if the username already exists
        if User.objects.filter(username=username).exists():
            messages.error(request, 'Username is already taken')
            return redirect('accounts:register')
        
        #Check if email already exists
        if User.objects.filter(email=email).exists():
            messages.error(request, 'Email is already registered')
            return redirect('accounts:register')
        
        #Create and save user
        user = User.objects.create_user(username=username,email=email, password=password1)
        user.save()

        messages.success(request, 'Registration Successful! You can now log in.')
        return redirect('accounts:login')
    return render(request, 'registration/register.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request,'Login Successful!')
            return redirect('shop:homepage')
        else:
            messages.error(request, 'Invalid username or password')
    return render(request, 'registration/login.html')

def logout_view(request):
    logout(request)
    messages.success(request,'You have been logged out.')
    return redirect('accounts:login')

accounts/templates/auth_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TommyTech Hub | {% block title %}Register{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/auth_style.css' %}">
    <script>
        document.addEventListener("DOMContentLoaded", function(){
        const passwordField = document.querySelector("#password");
        const passwordField1 = document.querySelector("#password1");
        const showPasswordToggle = document.querySelector(".showPasswordToggle");

        if (showPasswordToggle){
            showPasswordToggle.addEventListener("click", function(){
                if (passwordField.type === "password"){
                    showPasswordToggle.textContent = "HIDE";
                    passwordField.type = "text";
                    passwordField1.type = "text";
                }else{
                    showPasswordToggle.textContent = "SHOW";
                    passwordField.type = "password";
                    passwordField1.type = "password";
                }
            });
        }else{
            console.error("Element with class 'showPasswordToggle' not found");
        }
    });
    </script>
</head>
<body>
    <button class="toggle-mode" onclick="toggleMode()">🌙</button>

    <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="col-md-6">
            <div class="register-card text-white">
                {% block auth %}{% endblock auth %}
            </div>
        </div>
    </div>
    <script>
        function toggleMode() {
            document.body.classList.toggle("dark-mode");
            let btn = document.querySelector(".toggle-mode");
            if (document.body.classList.contains("dark-mode")) {
                btn.innerHTML = "☀️";
            } else {
                btn.innerHTML = "🌙";
            }
        }

        
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

    

accounts/templates/password_reset_complete.html
{% extends 'auth_base.html' %}
{% block title %}Password Rest Complete{% endblock title %}

{% block auth %}
<h2 class="text-white mb-3 text-center">Password Reset Complete</h2>
<p class="text-center">Your password has been successfully reset. You can now log in with your new password.</p>
<div class="d-flex justify-content-center">
 <a href="{% url 'accounts:login' %}" class="btn btn-primary w-10">Return to Login</a>
</div>
{% endblock auth %}

accounts/templates/password_reset_confirm.html
{% extends 'auth_base.html' %}
{% block title %}Set New Password{% endblock title %}

{% block auth %}
<h2 class="text-white mb-3 text-center">Set New Password</h2>
    <p class="text-center">Enter your new password below.</p>
	{% if form.errors %}
    <div class="messages.container">
        {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <a>{{error}}</a>
            </div>
			{% endfor %}
        {% endfor %}
    </div>
	{% endif %}
        <form method="post" >
         {% csrf_token %}
            <div class="mb-3">
                <input type="password" name="new_password1" id="password" placeholder= "New Password" class="form-control" required>
            </div>
            <div class="mb-3">
                 <input type="password" name="new_password2" id="password1" placeholder= "Confirm Password" class="form-control"required>
            </div>
            <div class="mb-3 text-end">
                <small style="cursor: pointer;" class="showPasswordToggle py-3 ">SHOW</small>
            </div>
            <button type="submit" class="btn btn-primary w-100 d-flex justify-content-center">Reset Password</button>
        </form
{% endblock auth %}

accounts/templates/password_reset_done.html
{% extends 'auth_base.html' %}
{% block title %}Password Rest Email Sent{% endblock title %}

{% block auth %}
<h2 class="text-white mb-3 text-center">Password Reset Email Sent</h2>
<p class="text-center">If an account with the email exists, you will receive a password reset link shortly.</p>
<div class="d-flex justify-content-center">
 <a href="{% url 'accounts:login' %}" class="btn btn-primary w-10">Return to Login</a>
</div>
{% endblock auth %}

accounts/templates/password_reset_email.html
{% autoescape off %}
<h2>Password Reset</h2>
<p>Click the link below to reset your password:</p>
<a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">Reset Password</a>

{% endautoescape %}

accounts/templates/password_reset_form.html
{% extends 'auth_base.html' %}
{% load static %}
{% block title %}Reset your password{% endblock title %}

{% block auth %}
<h2 class="text-white mb-3">Forgotten Password?</h2>
{% if messages %}
    <div class="messages.container">
        {% for message in messages %}
            {% if message.tags == 'error' %}
            <div class="alert alert-danger">
                <a>{{message}}</a>
            </div>
            {% elif message.tags == 'success' %}
            <div class="alert alert-success">
                <a>{{message}}</a>
            </div>
            {% else %}
            <div class="alert alert-info">
                <a></a>
            </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
<p class="text-center">Enter your email and we will send you a link to reset your password.</p>
<!-- Rest Password Form -->
<form method="post">
    {% csrf_token %}
    <!-- Email Input -->
    <div class="mb-3 input-group">
        <span class="input-group-text"><i class="fas fa-user"></i></span>
        <input type="email" class="form-control" placeholder="Enter your email" name="email">
    </div>
    <!-- Reset Link Button -->
    <button type="submit"  class="btn btn-primary w-100">Send Reset Link</button>

    <!-- Back To Login -->
    <div class="mt-3">
        <a href="{% url 'accounts:login' %}" class="text-white-50">Back to Login</a>
    </div>
</form>
{% endblock auth %}